### ISSUE TITLE
Kubernetes auto-discovery of pods to scale down

### ISSUE THREAD

**Issue by Nastaliss** [acouvreur/traefik-ondemand-service#27]
Hi !
I've done some improvements on the middleware side of this project while using it. We've been thinking of another improvement for this project on the service.
We're currently splitting our infrastructure in micro-services so our configuration is getting bigger and bigger.
Using Kubernetes, a great improvement would be to make the service automatically discover the pods to scale down.
Instead of providing the deployment's name, replica count and namespace of the targets to scale down we could instead provide a **label selector**, and let the service build its configuration on its own
I'd like to tackle this if you guys think it'd be an useful addition !

**Comment by acouvreur** [comment]
So this kind of an improvement of the multiple pods to scale model right ?
For k8s you'd add a label selector option to scale ?

I think that's a good idea, please open a PR :)
