### ISSUE TITLE
OnDemand-Service without docker

### ISSUE THREAD

**Issue by mgalloue** [acouvreur/traefik-ondemand-service#5]
Hi, 

I'm very interested by this kind of plugin but I'm not using docker. 
I just want to launch my stateless service on-demand using consul catalog.
Is it hard to have the same kind of plugin without docker ? I never code in go and I'm not using docker, so not sure were are the difficulties here.

Thanks for your help,

**Comment by acouvreur** [comment]
The actual scaler is fully integrated with Docker.
Docker provides an API to start and stop any application, which makes this a lot easier of course.

If you have a similar API, then I suppose it would be as easy.

Otherwise you'd need custom script for every application.
